-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZ6haNNCg3yNiTQCR
NiwLwXiOh0aJicw4QKuGd9bu0LmgCgYIKoZIzj0DAQehRANCAASTHwlhs+ktU6Yn
VI1Sg3lE37rvJjeBhlval4ZJtZ+l6qLJKUsHgOPiIOVq63ZyiwOHPtVU7OoVioGI
gMghUCoU
-----END PRIVATE KEY-----